// <auto-generated />
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180328120904_First-Migration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Model.House", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comfort");

                    b.Property<int>("Floor");

                    b.Property<string>("FurnishedAndFit");

                    b.Property<int>("LivingSurface");

                    b.Property<string>("Neighborhood");

                    b.Property<int>("NumberOfBathrooms");

                    b.Property<int>("NumberOfParkingSpaces");

                    b.Property<int>("NumberOfRooms");

                    b.Property<string>("Partitioning");

                    b.Property<bool>("PossibilityOfParking");

                    b.Property<int>("Price");

                    b.Property<string>("PropertyStatus");

                    b.Property<string>("PropertyType");

                    b.Property<int>("TotalNumberOfFloors");

                    b.Property<string>("YearBuilt");

                    b.HasKey("Id");

                    b.ToTable("Houses");
                });
#pragma warning restore 612, 618
        }
    }
}
